# Configuration settings for the Reddit multi-account bot system

accounts:
  - username: "bot_user_1"
    password: "password123"
    client_id: "CLIENT_ID_1"
    client_secret: "CLIENT_SECRET_1"
    user_agent: "bot1 user agent"
  - username: "bot_user_2"
    password: "password456"
    client_id: "CLIENT_ID_2"
    client_secret: "CLIENT_SECRET_2"
    user_agent: "bot2 user agent"

subreddits:
  - "example_subreddit1"
  - "example_subreddit2"

posting:
  interval: 3600  # seconds between posts

replies:
  chain_length: 1  # single reply

# OpenAI configuration for content generation
openai_api_key: "YOUR_OPENAI_API_KEY_HERE"
openai:
  post_prompt: "Generate an engaging Reddit post title and body."
  reply_prompt: "Generate a thoughtful reply to the following Reddit content:"

# Per-account personality settings (keyed by account username)
personalities:
  bot_user_1:
    description: "I am a college student who loves technology and gaming."
    memory: "I have extensive knowledge about college life, tech trends, and gaming."
  bot_user_2:
    description: "I am a power user with deep insights in business technology and productivity."
    memory: "I know a lot about advanced computing, business tech, and productivity tools."
